name: heartrate_database_u_i
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  http: ^1.2.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  flutter_svg: ^2.0.13
  flutter_dotenv: ^5.2.1
  timeago: ^3.7.0
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  flutter_downloader: ^1.11.8
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/svg/
    - assets/images/
    - .env
